<?php

/**
 * @var \Legendary\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) :
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
else: ?>
     <li class="create-account-link">
        <a href='<?php echo $block->getCreateAccountUrl(); ?>'><?php echo __("Create account"); ?></a>
     </li>";
     <li class="wishlist-link">
         <a href='<?php echo $block->getLoginUrl(); ?>'><?php echo __("Wishlist"); ?></a>
     </li>"
}
<?php endif; ?>

<li class="link authorization-link" data-label="<?= $block->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
        <?= /* @noEscape */ $dataPostParam ?>><?= $block->escapeHtml($block->getLabel()) ?></a>
</li>
