version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 88:80
      - 443:443
    volumes: &appvolumes
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/magento.conf:/etc/nginx/conf.d/magento.conf
      - ./nginx/ssl:/var/www/ssl
    depends_on:
      - database
      - php
    networks:
      - magento2-network

  database:
    image: mysql:5.7
    container_name: database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento23
      MYSQL_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - magento2-network

  php:
    build: ./php
    container_name: magento2_phpfpm
    #environment:
    #  - PHP_MEMORY_LIMIT=3048M
    #  - PHP_MAX_EXECUTION_TIME=300
    volumes:
      - ./src:/var/www/html
      - ./php/etc/php-fpm.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
    networks:
      - magento2-network

  #elasticsearch:
  #  image: elasticsearch:7.12.0
  #  container_name: magento2_elasticsearch
  #  environment:
  #    - cluster.name=docker-cluster
  #    - discovery.seed_hosts=es02,es03
  #    - bootstrap.memory_lock=true
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #  ulimits:
  #    memlock:
  #      soft: -1
  #      hard: -1
  #  volumes:
  #    - ./elasticsearchdata:/usr/share/elasticsearch/data
  #  ports:
  #    - 9200:9200
  #  networks:
  #    - magento2-network

  redis:
    image: redis
    container_name: magento2_redis
    ports:
      - 6379
    networks:
      - magento2-network

  redis-session:
    image: redis
    container_name: magento2_redis-session
    ports:
      - 6379
    networks:
      - magento2-network

  #varnish:
  #  container_name: varnish
  #  build:
  #    context: ./.docker/varnish/
  #  ports:
  #    - 6081:6081
  #  networks:
  #    - magento2-network
networks:
  magento2-network:
    driver: bridge

volumes:
  database_data:
    driver: local