<?php

/**
 * @var Mage2tv\Widget\Block\Main $block
 */

?>
<div data-bind="scope: 'root'">
    <div>Additional charge:
        <span data-bind="text: value"></span>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "root": {
                        "component": "Mage2tv_UI4/js/root",
                        "deps": ["root.sharedState"],
                        "children": {
                            "sharedState": {
                                "component": "Mage2tv_UI4/js/shared-state"
                            }
                        }
                    }
                }
            }
        }
    }
</script>
