<?php /** * @var Mage2tv\Widget\Block\Main $block */ ?> <div data-bind="scope: 'componente-a'"><h3 data-bind="text: label"></h3><div data-bind="text: amount"></div></div><div data-bind="scope: 'componente-b'"><h3 data-bind="text: title"></h3><div data-bind="text: value"></div></div><script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }</script>