<h1 > Hello Custom Template</h1 ><div data-bind="scope:'pulsestorm_nofrillslayout_chapter10_viewmodel'"><div ><!-- ko template : getTemplate () --><!-- /ko --></div ></div ><!-- START : add this code --><script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "pulsestorm_nofrillslayout_chapter10_viewmodel": {
                    "component": "Pulsestorm_Nofrillslayout/chapter10/user/view-model",
                    "template":  "Pulsestorm_Nofrillslayout/chapter10/hello-view-model",
                    "helloWorld":"Hola Muendo",
                    "config": {
                        "helloWorld":" Bonjour le monde "
                    }
                }
            }
        }
    }
}</script>