<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-11-29 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-12-04 11:07:49
 */
?>
<?php
/**
 * Categories block
 *
 * @var $block \Magepow\Categories\Block\Categories
 */

$categories  = $block->getCategories();
$heading     = $block->getHeading();
$description = $block->isShowDescription();
$itemAmount  = $block->getItemAmount();
if (empty($categories)) return;
$selector     = 'alo-content-'.uniqid();
?>
<?php $visible = (int) $this->getData('visible'); ?>
<style type="text/css"><?php echo $this->getData('slide') ? '.' . $selector . ' .item{float:left; width:' . 100/$visible . '%} .'. $selector . ' .item:nth-child(n+' . ++$visible . '){display: none}' : ''  ?></style>
<?php if ($heading): ?>
    <h3 class="title"><?php echo $heading ?></h3>
<?php endif; ?>
<div class="magepow-categories <?php echo $selector ?>">
    <ul class="owl-carousel owl-theme" id="owl-carousel2">
        <?php foreach ($categories as $cat): ?>
            <?php $image = $this->getImageInfo($cat); ?>
            <li class="category-item item">
                <div class="category-item-info">
                    <div class="category-image-container">
                        <a class="category-url" href="<?php echo $cat->getUrl() ?>">
                            <img src="<?php echo $this->getImage($cat) ?>" width="<?php echo $image->getOriginalWidth() ?>" height="<?php echo $image->getOriginalHeight() ?>" alt="<?php echo $cat->getName() ?>"/>
                        </a>
                    </div>
                    <div class="category-item-details">
                        <h3 class="category-item-name">
                            <a class="category-item-link" href="<?php echo $cat->getUrl() ?>">
                                <span class="category-name"><?php echo $cat->getName() ?></span>
                            </a>
                        </h3>

                        <?php if($description): ?>
                            <div class="category-description">
                                <?php echo $this->getDescription($cat) ?>
                            </div>
                        <?php endif; ?>
                        <?php if($itemAmount): ?>
                            <div class="category-item-amount">
                                    <?php echo "(".$cat->getProductCollection()->count();
                                        if($cat->getProductCollection()->count()>0)echo " items)";
                                        else echo " item)";
                                    ?>
                            </div>
                        <?php endif; ?>

                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<script>
    require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {
        $('#owl-carousel2').owlCarousel({

            margin:0,
            responsiveClass:true,
            items :1,
            navText:	["prev","next"],
            dots: false,
            touchDrag: false,
            mouseDrag: false,

            responsive:{
                0:{
                    items:1,
                    nav:true
                },
                480:{
                    items:3,
                    nav:false
                }
            }
        });

        // jQuery('.owl-next').trigger('click');

    });
</script>
