<?php

/**
 * @var Mage2tv\Widget\Block\Main $block
 */

 $imageUrl = $block->getViewFileUrl('Mage2tv_UI5/images/img1.jpg');
?>

<div scope="my-component">
    <h1 data-mage-init='{"Mage2tv_UI5/js/plain/pixelbg" : {
                            "src": "<?php echo $imageUrl ?>",
                            "pixelSize": 10
    }}'>
        lala land lala land lala land lala land lala land lala land
    </h1>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "my-component": {
                        "component": "Mage2tv_UI4/js/viewmodel",
                        "template": "Mage2tv_UI4/button"
                    }
                }
            }
        }
    }
</script>
