<?php /** * @var Mage2tv\Widget\Block\Main $block */ ?> <div data-bind="scope: 'translate'"><!-- ko template: getTemplate() --><!-- /ko --></div><script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "translate": {
                        "component": "Mage2tv_Translate/js/ui-component",
                        "template": "Mage2tv_Translate/localized-template"
                    }
                }
            }
        }
    }</script>