<?php /** @var Legendary\Swatches\Block\Product\Renderer\Configurable $block */ /** @var \Magento\Swatches\ViewModel\Product\Renderer\Configurable $configurableViewModel */ $configurableViewModel = $block->getConfigurableViewModel(); $handles = $block->getLayout()->getUpdate()->getHandles(); $isProductPage = false; foreach ($handles as $handle) { if($handle === 'catalog_product_view') { $isProductPage = true; } } ?> <div class="swatch-opt" data-role="swatch-options"></div><script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $block->escapeJs($block->escapeUrl($block->getMediaCallback())) ?>",
                "gallerySwitchStrategy": "<?= $block->escapeJs($block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct')) ?: 'replace'; ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>,
                "showTooltip": <?= $block->escapeJs($configurableViewModel->getShowSwatchTooltip()) ?>,
                "isProductPage": "<?= $isProductPage ?>"
            }
        },
        "*" : {
            "Magento_Swatches/js/catalog-add-to-cart": {}
        }
    }</script>