<?php

/**
 * @var Mage2tv\Js\Block\Main $block
 */

$url = $block->escapeJs($block->getBaseUrl());

?>


<form action="" data-mage-init='{"validation": {}}'>
    <div class="control">
        <input type="text"
               name="email"
               id="email"
               class="input-text"
               placeholder="<?= __('your email') ?>"
               data-validate="{required: true, 'validate-email': true}" />
    </div>
    <button type="submit" class="action primary"><?= __('Submit') ?></button>
</form>
