<?php

/**
 * @var Mage2tv\Widget\Block\Main $block
 */

?>
<div data-bind="scope: 'exampleUiComponent3'">
    <h3 data-bind="text: label"></h3>
    <table data-bind="foreach: items">
        <tr>
            <td data-bind="text: name"></td>
            <td data-bind="text: qty"></td>
            <td data-bind="text: price"></td>
            <td data-bind="text: $parent.rowTotal($data)"></td>
        </tr>
    </table>
    <div>Additional charge: <span data-bind="text: additional_charge"></span></div>
    <strong>Total: <span data-bind="text: total()"></span></strong>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "exampleUiComponent3": {
                        "component": "Mage2tv_UI3/js/ui-component"
                    }
                }
            }
        }
    }
</script>
