<?php

/**
 * @var Mage2tv\Widget\Block\Main $block
 */

?>
<div data-bind="scope: 'component-a'">
    <h3 data-bind="text: label"></h3>
    <div data-bind="text: amount"></div>
</div>

<div data-bind="scope: 'component-b'">
    <h3 data-bind="text: title"></h3>
    <div data-bind="text: value"></div>
    <div data-bind="text: fromExport"></div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "component-a": {
                        "component": "Mage2tv_UI3/js/ui-component-a"
                    },
                    "component-b": {
                        "component": "Mage2tv_UI3/js/ui-component-b"
                    }
                }
            }
        }
    }
</script>
